title: Science Generalization Hypothesis
description: A book by Yousef Yousefi
theme: minima
plugins:
  - jekyll-seo-tag
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
      nav_order: 1
